# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
before-install:
  - sudo apt install cppcheck
  - sudo apt install valgrind
    
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - cd Identifier; make
  - cd Identifier; make cov
  - cd Identifier; make cppcheck
#  - make test
